### ISSUE TITLE
Sigma Value Modifiers

### ISSUE THREAD

**Issue by PiRomant** [theflakes/sigma_to_wazuh#21]
Rule without value [modifiers](https://sigmahq.io/docs/basics/modifiers.html)
```yaml
detection:
    selection:
        EventID:
            - 150
            - 770
            - 771
  ```
converts to
```xml
<field name="win.system.eventID" negate="no" type="pcre2">(?i)150|770|771</field>
```
instead of
```xml
<field name="win.system.eventID" negate="no" type="pcre2">(?i)^150$|^770$|^771$</field>
```
Could cause false positive with eventID = `1500`, `1150`...
It may also affect performance.
Rule source: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/dns_server/win_dns_server_susp_server_level_plugin_dll.yml#L25-L28
